/* Auto-generated by doc2code — do not edit by hand */

export interface AnimTokens {
  bandSpeed: number;
  bandSpread: number;
  bandMix: number; // 0..100
  symbolSet: string[];
  autoplay: boolean;
  playhead: number; // 0..100
}

export const DEFAULT_SYMBOLS = [
  '\u2800','\u2802','\u2804','\u2806','\u2810','\u2812','\u2814','\u2816',
  '\u2820','\u2822','\u2824','\u2826','\u2830','\u2832','\u2834','\u2836',
] as const;

export interface LMStreamParams {
  contextText: string;
  band: { start: number; end: number };
  maxNewTokens: number;
}
