/* Auto-generated by doc2code — do not edit by hand */

export interface LMStreamParams {
  text: string;
  caret: number;
  active_region: { start: number; end: number };
  settings?: Record<string, unknown>;
}

export interface AnimTokens {
  waveSpeed: number;
  waveSpread: number;
  waveMix: number; // 0..100
  symbolSet: string[];
  autoplay: boolean;
  playhead: number; // 0..100
}

export const DEFAULT_SYMBOLS = [
  '\u2800','\u2802','\u2804','\u2806','\u2810','\u2812','\u2814','\u2816',
  '\u2820','\u2822','\u2824','\u2826','\u2830','\u2832','\u2834','\u2836',
] as const;
