name: MindType CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Rust Format
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Eslint
        run: pnpm --prefix web-demo lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run Rust tests
        run: cargo test --workspace
      - name: Run web-demo tests
        run: pnpm --prefix web-demo test
      - name: Run e2e tests
        run: pnpm --prefix e2e test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build WASM
        run: wasm-pack build crates/core-rs --target web --out-dir bindings/wasm/pkg
      - name: Build web-demo
        run: pnpm --prefix web-demo build
